import './globals.css'
import type { Metadata } from 'next'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        {/* Import Map */}
        {/* <script type="importmap">
          {`
          {
            "imports": {
              "three": "https://cdn.jsdelivr.net/npm/three@0.161.0/build/three.module.js",
              "jsm/": "https://cdn.jsdelivr.net/npm/three@0.161.0/examples/jsm/"
            }
          }
          `}
        </script> */}
      </head>
      <body>{children}</body>
    </html>
  )
}
